[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/index.js"
  status = 200
  force = true

